version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    privileged: true
    user: root
    ports:
    - "8080:8080"
    - "50000:50000"
    container_name: jenkins
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
    networks: 
      default:
        ipv4_address: "172.20.0.3"
    
  git-serve:
    build:
      context: .
      dockerfile: gitserve.dockerfile
    container_name: git-serve
    ports:
    - "22:22"
    - "80:80"
    networks: 
      default:
        ipv4_address: "172.20.0.2"


networks:
  default:
    ipam:
      config:
        - subnet: "172.20.0.0/16"