version: '3.8'

services:
  dhcpd:
    build: .
      restart: unless-stopped
      networks:
        internal_network:
          ipv4_address: 192.168.16.1

        volumes:
          - ./dhcpd.conf:/etc/dhcp/dhcpd.conf

networks:
  internal_network:
    driver: bridge
        