name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: chmod
      run: chmod u+x ./runAll.sh
    - name: run all make
      run: ./runAll.sh
